### ISSUE TITLE
Make a cat tool to display the first few records in a parquet file

### ISSUE THREAD

**Issue by julienledem** [Parquet/parquet-mr#114]

**Comment by arunk1234** [comment]
I used the show schema command. It worked for regular non-compressed parquet file. Does it work with the snappy or other compressed parquet files. Tried with snappy.parquet file, got message{ read binary data line}

**Comment by andreweduffy** [comment]
Can this be closed or are there still things going on here?

**Comment by julienledem** [comment]
the issues on https://github.com/Parquet/parquet-mr are for reference only. Since the project has moved to apache we use the apache JIRA: https://issues.apache.org/jira/browse/PARQUET and pull request on the apache github mirror: https://github.com/apache/parquet-mr
