### ISSUE TITLE
Snappy decompression is terribly slow

### ISSUE THREAD

**Issue by NathanHowell** [Parquet/parquet-mr#211]
I found that query performance in Hive+Parquet using Snappy to be slower than GZip and LZMA2. I hacked together a [quick & dirty profiler](https://gist.github.com/NathanHowell/45397d9deeb326f35652) and it seems that [`SnappyDecompressor`](https://github.com/Parquet/parquet-mr/blob/master/parquet-hadoop/src/main/java/parquet/hadoop/codec/SnappyDecompressor.java) falls over with blocks larger than 64KB... this seems related to the block compression completed in #70. Compression times appear to be unaffected.
### Round-trip (Compress -> Decompress) Times

| Size | GZip | LZMA2 | Snappy |
| --- | --- | --- | --- |
| 1 | 0.205 | 21.319 | 0.061 |
| 4 | 0.17 | 21.198 | 0.061 |
| 16 | 0.174 | 26.052 | 0.057 |
| 64 | 0.167 | 20.943 | 0.053 |
| 256 | 0.186 | 21.26 | 0.062 |
| 1024 | 0.213 | 22.114 | 0.063 |
| 4096 | 0.263 | 23.019 | 0.084 |
| 16384 | 0.515 | 26.329 | 0.169 |
| 65536 | 2.182 | 36.722 | 0.847 |
| 262144 | 9.338 | 82.919 | 6.701 |
| 1048576 | 35.852 | 281.327 | 144.625 |
| 4194304 | 153.298 | 1208.784 | 2228.986 :frowning: |
| 16777216 | 616.207 | 6194.507 | 25174.856 :cry: |
| 67108864 | 2487.626 | 26794.818 | 347293.631 :rage: |
### Compression Times

| Size | GZip | LZMA2 | Snappy |
| --- | --- | --- | --- |
| 1 | 0.127 | 19.47 | 0.057 |
| 4 | 0.171 | 18.198 | 0.042 |
| 16 | 0.125 | 18.199 | 0.041 |
| 64 | 0.124 | 19.29 | 0.041 |
| 256 | 0.143 | 18.237 | 0.043 |
| 1024 | 0.192 | 18.025 | 0.046 |
| 4096 | 0.219 | 19.067 | 0.066 |
| 16384 | 0.477 | 21.918 | 0.134 |
| 65536 | 2.179 | 34.145 | 0.405 |
| 262144 | 8.891 | 79.189 | 1.745 |
| 1048576 | 35.622 | 271.167 | 6.205 |
| 4194304 | 143.754 | 1199.246 | 22.254 |
| 16777216 | 596.729 | 6150.707 | 87.116 |
| 67108864 | 2401.637 | 26464.005 | 339.957 |

**Comment by juanpampliega** [comment]
Hi, just wanted to check.. is this problem still affecting newer Hive versions?

The recommended workaround for the moment is to set `parquet.page.size=32000`?

**Comment by NathanHowell** [comment]
@juanpampliega It would be best to rerun the benchmarks with newer versions of parquet-mr and/or snappy-java to see if it's still problematic

**Comment by julienledem** [comment]
@
