### ISSUE TITLE
Parquet should support the timestamp data type

### ISSUE THREAD

**Issue by avisitor** [Parquet/parquet-mr#218]
timestamp is supported as a data type in Hive since 0.8 but it is not supported in Java parquet-mr 1.2.5. It is supported in Impala with Parquet.

Pig has DateTime since 0.11 and that is not supported in parquet-mr 1.2.5, either.

Timestamp or DateTime is valuable for use in date and time expressions.

**Comment by jmssil** [comment]
Hi,

Does anyone have any news on this limitation?

Do you confirm that it is not yet supported with Hive 1.2.1.2.4?

Thanks.

**Comment by Tagar** [comment]
No support for timezones?

**Comment by julienledem** [comment]
please use https://issues.apache.org/jira/browse/PARQUET
This repo is there for historical purposes.
https://github.com/apache/parquet-format/blob/master/LogicalTypes.md#datetime-types
