### ISSUE TITLE
Decouple Parquet from Hadoop API

### ISSUE THREAD

**Issue by julienledem** [Parquet/parquet-mr#305]
To allow reading and writing Parquet files independently of the Hadoop APIs.

**Comment by jmd1011** [comment]
Has this effort been abandoned, or is this still on the radar?

**Comment by julienledem** [comment]
@jmd1011 Nobody is working on it that I know of. You're welcome to propose something.
Please use https://issues.apache.org/jira/browse/PARQUET as this repo is deprecated

**Comment by l15k4** [comment]
@jmd1011 Hey, is this effort going anywhere or you gave up :-) https://github.com/jmd1011/parquet-readers

I would be so nice to use hadoopless parquet

**Comment by jmd1011** [comment]
I am still working on this, yup! Things are just coming along slower than anticipated.

**Comment by spetsnaz84** [comment]
Any update on this one ?

**Comment by julienledem** [comment]
Parquet development has moved to apache:
https://issues.apache.org/jira/browse/PARQUET
https://github.com/apache/parquet-mr
