### ISSUE TITLE
Protobuf version

### ISSUE THREAD

**Issue by davidzchen** [Parquet/parquet-mr#326]
I noticed that parquet-protobuf depends on Protobuf 2.4.1. Is it possible to bump this dependency to Protobuf 2.5.0? This is the version used by many other Hadoop projects including Hadoop2/YARN and Tajo, but unfortunately, the generated classes for 2.4.1 are not compatible with Protobuf 2.5.

**Comment by mfirry** [comment]
Any chance to have a version for Protocol Buffers v3.0.0?

**Comment by julienledem** [comment]
You can open a PR on https://github.com/apache/parquet-mr
