### ISSUE TITLE
parquet-pig should not throw an exception reading a timestamp from impala file

### ISSUE THREAD

**Issue by gpolaert** [Parquet/parquet-mr#435]
Releated to #218.

Hi, I need to load impala table with timestamp columns with pig. I think loading timestamp cols is still a NYI feature.  Waiting for #218 TBD, pig-parquet should not throw an exception but at least should bind Int96 into a bytearray (users can write their own UDF to convert it into pig datetime type). 
Is there anyone working on the same thing ?

**Comment by julienledem** [comment]
we don't use this repo anymore. It is here for historical purpose.
Please open a PARQUET jira: https://issues.apache.org/jira/browse/PARQUET
