### ISSUE TITLE
How to append data to a  parquet file already exists

### ISSUE THREAD

**Issue by Fly365** [Parquet/parquet-mr#454]
hello:
   How to append data to a  parquet file already exists,but the writer is already close,when i writer the exists file,covering the file,so i don‘t know how to do it ,pleases help me ,thank you!!!

**Comment by Tracy6465** [comment]
have you solved this problem?

**Comment by Fly365** [comment]
没有，使用其他方式进行处理的，一是可以在内存中缓存数据，然后写到parquet文件中；另外，人为定时合并小的parquet文件

**Comment by Tracy6465** [comment]
方便分享下吗

**Comment by Fly365** [comment]
处理方式不一样，我缓存的spark的RDD，然后通过Spark SQL写到对应文件的

**Comment by Fly365** [comment]
他有推荐的块大小，太大和太小都不好的，你可以按照hadoop的hdfs块大小或整数倍来进行存储
