### ISSUE TITLE
Failed: Dump few cols of the file using parquet-tools dump -c

### ISSUE THREAD

**Issue by daralisp** [Parquet/parquet-mr#456]
Im trying to retrieve few cols from parquet file but seems never work. Could you please help. \
hadoop jar parquet-tools-1.8.1.jar dump -c c2 part-r-00000.gz.parquet
Warning: $HADOOP_HOME is deprecated.

Invalid arguments: missing required arguments

usage: parquet-dump [option...] <input>
where option is one of:
    -c,--column <arg>  Dump only the given column, can be specified more than
                       once
    -d,--disable-data  Do not dump column data
       --debug         Enable debug output
    -h,--help          Show this help string
    -m,--disable-meta  Do not dump row group and page metadata
       --no-color      Disable color output even if supported
where <input> is the parquet file to print to stdout

**Comment by julienledem** [comment]
parquet development has moved to apache:
https://github.com/apache/parquet-mr
https://issues.apache.org/jira/browse/PARQUET
