### ISSUE TITLE
add Kerberos authentication support for HDFS access

### ISSUE THREAD

**Issue by Tagar** [Parquet/parquet-mr#458]
It would be awesome for parquet-tools to have native Kerberos support.

> $ /usr/bin/parquet-tools schema hdfs://pc1udatahad05/hivewarehouse/disc_dv.db/odi_amf_trans_dv_04112016/000000_0
> SIMPLE authentication is not enabled.  Available:[TOKEN, KERBEROS]

**Comment by julienledem** [comment]
parquet development has moved to apache:
https://github.com/apache/parquet-mr
https://issues.apache.org/jira/browse/PARQUET
