### ISSUE TITLE
Build fails for parquet-tools

### ISSUE THREAD

**Issue by jldupont** [Parquet/parquet-mr#459]
Whilst attempting to build https://github.com/Parquet/parquet-mr/tree/master/parquet-tools , I get the following error:

> [ERROR] Failed to execute goal on project parquet-tools: Could not resolve dependencies for project com.twitter:parquet-tools:jar:1.6.0rc3-SNAPSHOT: Could not find artifact com.twitter:parquet-hadoop:jar:1.6.0rc3-SNAPSHOT in sonatype-nexus-snapshots (https://oss.sonatype.org/content/repositories/snapshots) -> [Help 1]

**Comment by eleniS** [comment]
Try the solution suggested here: https://github.com/Parquet/parquet-mr/issues/444#issuecomment-221524347
