### ISSUE TITLE
Specify column encoding when converting protobuf to parquet?

### ISSUE THREAD

**Issue by costimuraru** [Parquet/parquet-mr#463]
Hi guys,

When converting a protobuf message to parquet, using a `ProtoParquetWriter`, is it possible to specify different kind of parquet encodings (eg. delta, dictionary, RLE etc. [1]) for the columns defined in the protobuf schema?

Example protobuf schema:
```
message MyProtobufMessage {
    int64 timestamp = 1;
    int32 value_that_keeps_repeating = 2;
    string server_ip = 3;
}
```

We want to leverage the fact that timestamp is sorted and can be encoded using Delta, server_ip can be used with a dictionary encoding, value_that_keeps_repeating can be encoded using RLE and so forth [2].

Appreciate any help here.

Related issue: https://github.com/Parquet/parquet-mr/issues/318

[1] https://github.com/Parquet/parquet-format/blob/master/Encodings.md
[2] https://www.slideshare.net/julienledem/how-to-use-parquet

**Comment by julienledem** [comment]
parquet development has moved to apache:
https://github.com/apache/parquet-mr
https://issues.apache.org/jira/browse/PARQUET
