### ISSUE TITLE
issue facing while reading parquet file having decimal data type in map reduce

### ISSUE THREAD

**Issue by ganesh420** [Parquet/parquet-mr#464]
Hi ,

I am reading parquet file present in impala in map reduce.The schema of the table is having decimal datatype and other data types.

I am using **ParquetInputFormat** to parse parquet records.In mapper,i am getting  all the column value except decimal. The decimal data type is in non-readable binary format which I am trying to convert into double is giving some other value.

Can you help me out??

**Comment by julienledem** [comment]
parquet development has moved to apache:
https://github.com/apache/parquet-mr
https://issues.apache.org/jira/browse/PARQUET
